version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment: 
      POSTGRES_DB: "lucas_database"
      POSTGRES_USER: "lucas"
      POSTGRES_PASSWORD: "lucas123"
    ports:
      - 5432:5432
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: lucas@teste.com
      PGADMIN_DEFAULT_PASSWORD: lucas123
    ports:
      - 8080:80
    depends_on:
      - postgres